import type { Employer, Source } from "./types.ts";
import { employerRegistry } from "./batches.ts";

export const employers: Employer[] = [
  { id: "afreximbank", name: "Afreximbank / FEDA", aliases: ["Afreximbank", "African Export-Import Bank", "FEDA", "Fund for Export Development in Africa"], logoUrl: "/logos/afreximbank.jpg" },
  { id: "pula", name: "Pula", aliases: ["Pula Advisors", "Pula" ] },
  { id: "proparco", name: "Proparco", aliases: ["Proparco"] },
];

export const sources: Source[] = [
  { id: "afreximbank-careers", employerId: "afreximbank", type: "official_careers", url: "https://www.afreximbank.com/our-bank/careers/", priority: 1, required: true, active: true, accessMethod: "web_page", lastVerified: "2026-08-28", expectedCoverage: "Career context and official route", notes: "Official careers page; the ATS adapter is the vacancy source." },
  { id: "afreximbank-workable", employerId: "afreximbank", type: "official_ats", url: "https://apply.workable.com/afreximbank/jobs.md", priority: 1, required: true, active: true, accessMethod: "http_markdown", lastVerified: "2026-08-28", expectedCoverage: "All public Workable openings, including FEDA roles", notes: "Official Afreximbank Workable markdown vacancy feed." },
  { id: "afreximbank-linkedin-company", employerId: "afreximbank", type: "linkedin_company", url: "https://www.linkedin.com/company/afreximbank/", priority: 3, required: true, active: true, accessMethod: "manual_review", lastVerified: "2026-08-28", expectedCoverage: "Public company posts only when accessible", notes: "No authenticated or automated LinkedIn access." },
  { id: "afreximbank-linkedin-jobs", employerId: "afreximbank", type: "linkedin_jobs", url: "https://www.linkedin.com/company/afreximbank/jobs/", priority: 3, required: true, active: true, accessMethod: "manual_review", lastVerified: "2026-08-28", expectedCoverage: "Partial, public indexed job visibility", notes: "Manual LinkedIn review required." },
  { id: "pula-careers", employerId: "pula", type: "official_careers", url: "https://www.pula-advisors.com/career", priority: 1, required: true, active: true, accessMethod: "web_page", lastVerified: "2026-08-28", expectedCoverage: "Career context and official route", notes: "Official Pula careers page." },
  { id: "pula-bamboohr", employerId: "pula", type: "official_ats", url: "https://pula.bamboohr.com/careers/list", priority: 1, required: true, active: true, accessMethod: "http_json", lastVerified: "2026-08-28", expectedCoverage: "All public BambooHR job openings", notes: "Official Pula BambooHR JSON listing and details endpoints." },
  { id: "pula-linkedin-company", employerId: "pula", type: "linkedin_company", url: "https://www.linkedin.com/company/pula-advisors/", priority: 3, required: true, active: true, accessMethod: "manual_review", lastVerified: "2026-08-28", expectedCoverage: "Public company posts only when accessible", notes: "Manual LinkedIn review required." },
  { id: "pula-linkedin-jobs", employerId: "pula", type: "linkedin_jobs", url: "https://www.linkedin.com/company/pula-advisors/jobs/", priority: 3, required: true, active: true, accessMethod: "manual_review", lastVerified: "2026-08-28", expectedCoverage: "Partial, public indexed job visibility", notes: "Manual LinkedIn review required." },
  { id: "proparco-careers", employerId: "proparco", type: "official_careers", url: "https://www.proparco.fr/en/careers", priority: 1, required: true, active: true, accessMethod: "web_page", lastVerified: "2026-08-28", expectedCoverage: "Career context and official route", notes: "Official Proparco careers content." },
  { id: "proparco-cornerstone", employerId: "proparco", type: "official_ats", url: "https://afd.csod.com/ux/ats/careersite/5/home?c=afd&lang=en-US", priority: 1, required: true, active: true, accessMethod: "web_page", lastVerified: "2026-08-28", expectedCoverage: "AFD/Proparco public vacancies when search endpoint is available", notes: "Official AFD Cornerstone ATS. Public API endpoint requires further adapter work." },
  { id: "proparco-linkedin-company", employerId: "proparco", type: "linkedin_company", url: "https://www.linkedin.com/company/proparco/", priority: 3, required: true, active: true, accessMethod: "manual_review", lastVerified: "2026-08-28", expectedCoverage: "Public company posts only when accessible", notes: "Manual LinkedIn review required." },
  { id: "proparco-linkedin-jobs", employerId: "proparco", type: "linkedin_jobs", url: "https://www.linkedin.com/company/proparco/jobs/", priority: 3, required: true, active: true, accessMethod: "manual_review", lastVerified: "2026-08-28", expectedCoverage: "Partial, public indexed job visibility", notes: "Manual LinkedIn review required." },
  ...employerRegistry.employers.flatMap((employer) => employer.otherVerifiedSources.map((source) => ({ id: `registry-${source.id}`, employerId: employer.id, type: source.type, url: source.url, priority: source.required ? 1 : 2, required: source.required, active: false, accessMethod: source.accessMethod, lastVerified: "", expectedCoverage: "Configured from the researched employer workbook; manual source setup is still required.", notes: employer.manualReviewNotes } satisfies Source))),
];

employers.push(...employerRegistry.employers.map((employer) => ({ id: employer.id, name: employer.displayName, aliases: employer.aliases })));
